- setup.py
- tap_zuora/__init__.py
Use singer-python 1.6.0 and the new metrics format it brings. Example output:
```
INFO METRIC: {"metric": "http_request_duration", "type": "timer", "tags": {"endpoint": "export_create", "status": "succeeded"}, "value": 0.9041447639465332}
INFO METRIC: {"metric": "http_request_duration", "type": "timer", "tags": {"endpoint": "export_poll", "status": "succeeded"}, "value": 0.33080124855041504}
INFO METRIC: {"metric": "job_duration", "type": "timer", "tags": {"job_type": "export_attempt", "status": "succeeded"}, "value": 0.33103275299072266}
INFO METRIC: {"metric": "job_duration", "type": "timer", "tags": {"job_type": "export", "status": "succeeded"}, "value": 1.4924097061157227}
INFO METRIC: {"metric": "http_request_duration", "type": "timer", "tags": {"endpoint": "export_create", "status": …
```
> Use new singer-python metrics format

- tap_zuora/__init__.py
- tap_zuora/apis.py
Zuora's documentation describes some objects not supporting deleted records:
https://knowledgecenter.zuora.com/DC_Developers/T_Aggregate_Query_API/B_Submit_Query/a_Export_Deleted_Data
After testing, we found the list to not be 100% accurate - AccountingCode works with deleted despite what the document shows.
When an object does not support them, the error will be:
> Objects included in the queries do not support the querying of deleted records. Remove Deleted section in the JSON request and retry the request
> Fix zuora deleted objects

- tap_zuora/apis.py
- tap_zuora/discover.py
When we add fields from joined objects, we want to drop the '.' in the field name.  However, when we query the API, we need to have the '.' present.  
This PR adds metadata to determine which fields need to have the '.' added when querying.
> fixing the joined object field names in the request

- tap_zuora/sync.py
This makes it so that the retry logic for AQuA streams that time out is repeated in the same tap run, allowing it to complete successfully much quicker than otherwise.
> Refactor and add a retry loop for timed out aqua streams.

- tap_zuora/sync.py
Found out that if a weird record comes back from Zuora and its missing a bookmark, we'll end up writing a null bookmark to our state which wipes out how far we've gone.
> Skip writing a bookmark if the record has none

- tap_zuora/client.py
If a TCP socket is left open for too long (~2 hours), Zuora will snap the connection. This adds a retry to the Session object's HTTPHandler in order to re-open the socket with a single retry in the event of a snapped connection.
> Attempt to retry once if TCP socket closes due to session timeout

- tap_zuora/sync.py
Zuora clears out exported files every 72 hours. If for some reason, we have a state value that contains one of these, and it ages out. It will never be replicated.
In the event that Zuora returns a 404 for a file, this PR will make the tap save state with the ID removed, and fail out, to be retried the next time around.
An important note is that the tap will not continue, since it wasn't able to retrieve the data for that file, so on the next run it will retry the range from the bookmark value present.
> Remove file id from state and exit in the event of a 404

- tap_zuora/apis.py
It appears that in some cases, the Zuora API will silently return 0 records in the case where the ZOQL date format is not `YYYY-mm-ddTHH:MM:ss` with the "T" delimiter. This has been confirmed by Zuora support themselves as the cause of this issue, and is indicated in [this piece of documentation](https://knowledgecenter.zuora.com/DC_Developers/BB_Export_ZOQL/G_Dates_and_Datetimes).
It's unclear why this works sometimes, but in testing, it appears to work the same given the other, so my expectation is that there is an edge case in the Zuora backend.
This PR changes the date format for ZOQL exports from the AQuA API to match this style.
> Use T delimited format for ZOQL AQuA export queries

- tap_zuora/apis.py
- tap_zuora/sync.py
We were seeing an issue where our query was being interpreted as the timezone of the account holder,  and we were bookmarking based off of the returned data (in UTC), which led to data discrepancies.  
This PR adds the timezone to the query to ensure its interpreted as UTC.
> Add timezone to AQuA queries

- tap_zuora/apis.py
This change is very much like #37.
All configurations of the timezone change were tested and the one in this PR returned the most data.
And by all configurations, I mean:
- Given that the query looks like `a <= b < c`, I used the same bookmark to make the following queries:
- `a <= b < c`
- `a (+00:00) <= b < c`
- `a <= b < c (+00:00)`
- `a (+00:00) <= b < c (+00:00)`
> Add timezone info to REST queries

- tap_zuora/client.py
Fixes #40
Tests passing and metrics captured:
```
2019-06-22 23:27:11,694Z    tap - INFO POST: https://apisandbox.zuora.com/apps/api/batch-query/
2019-06-22 23:27:13,867Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=2.1726622581481934, tags={'endpoint': 'apps/api/batch-query/', 'status': 'succeeded'})
2019-06-22 23:27:13,871Z    tap - INFO GET: https://rest.apisandbox.zuora.com/v1/describe/TaxationItem
2019-06-22 23:27:14,061Z    tap - INFO METRIC Point(metric_type='timer', metric='http_request_duration', value=0.19077849388122559, tags={'endpoint': 'v1/describe/TaxationItem', 'status': 'succeeded'})
```
> Add http_request_timer to API calls

- tap_zuora/apis.py
This PR follows Zuora's recommendation to make the timestamps in the tap queries ISO 8601 timestamps.
- 
- Low
> Remove timezone from query

- tap_zuora/sync.py
When we encounter a truncated CSV get a new stateful query session.
The Zuora API can sometimes send us a non-rectangular CSV file (ie the number if items in a row is less than the number of columns). Testing has shown that when this happens in a stateful AQuA session then that session will from then on continuously return non-rectangular CSV.
This tap uses the `version` bookmark as part of the key for the AQuA query session. By generating a new `version` bookmark the tap ensures that on the next sync after encountering the non-rectangular CSV it will get a new query session.
- Ran this on a connection that was receiving this `non-rectangular` exception. Running on this branch the tap encountered the exception once and fixed its state. On the subsequent run it was able to complete the …
> When we encounter a truncated CSV get a new stateful query session

- tap_zuora/apis.py
Currently, our REST api queries are not specifying a timezone. Based on code elsewhere in the tap, it looks like we assume no timezone specified means UTC, but we were seeing behavior where that wasn't the case. This change explicitly forces UTC.
See https://knowledgecenter.zuora.com/Central_Platform/Query/Export_ZOQL/G_Dates_and_Datetimes#Specify_time_zones for more info 
- I ran a sync that queried the span of an hour and didn't get a known existing record with an updated at within that hour. I then ran a sync that queried the span of that hour, plus three hours before that hour. This sync did get the missing record.
- I ran the same initial sync that spanned one hour with this change, and the record showed up properly.
- Low
> Enforce utc in queries in REST api

- CHANGELOG.md
- setup.py
See #56 
Change datetimes in REST queries to explicitly use UTC
- 
- 
> bump 1.2.4

- CHANGELOG.md
- setup.py
- tap_zuora/sync.py
This timeout appears arbitrary, and isn't based on any inability of Zuora to fulfill this request. In the event that a stream just has a ton of data in it, the timeout can keep recurring and look like the tap is dead in the water.
This PR attempts to avoid this scenario by simply increasing the timeout by a lot, rather than introducing any complicated retry counting logic, bailout logic, or some kind of expo backoff.
- None relying on automation coverage for a smoke test
- Low, this is just the increase of an existing value. Impact is scoped to the sync file.
- revert this branch, release new patch version
> Increase aqua job timeout to 12 hrs

- CHANGELOG.md
- setup.py
- tap_zuora/discover.py
Adds `UNAVAILABLE_STREAMS` to skip during discovery. In Support tickets, BillingPreviewRun during discovery `key_property: Id` was not in discovered fields. 
From the logs we see that  BillingPreviewRun.Id is not available for export, along with most of the fields of any value. 
> tap - INFO BillingPreviewRun.AssumeRenewal not available for export
> tap - INFO BillingPreviewRun.Batches not available for export
> tap - INFO BillingPreviewRun.ChargeTypeToExclude not available for export
> tap - INFO BillingPreviewRun.CreatedById not available for export
> tap - INFO BillingPreviewRun.CreatedDate not available for export
> tap - INFO BillingPreviewRun.EndDate has an unsupported data type
> tap - INFO BillingPreviewRun.ErrorMessage not available for export
> tap - INFO BillingPreviewRun.Id …
> skip BillingPreviewRun stream during discovery

- CHANGELOG.md
- setup.py
- tap_zuora/discover.py
Latest release of 1.4.0 is breaking for certain client while discovering BillingPreviewRun
Instead of breaking loop, we should return empty dict
-
Low, this is client specific.
> Return empty dict for non-discoverable stream

- tap_zuora/discover.py
- tests/base.py
- tests/test_zuora_discovery.py
Related Object identifiers are not necessarily queryable with a given object. If a field is known to cause issues when included as a related object, do not add that field to a stream's field_dict.
- Tested with cloned connection
- Low; these fields cannot be queried on related objects currently.
> TDL-21785 Don't add related object to field_dict if unqueryable

- CHANGELOG.md
- setup.py
- tap_zuora/discover.py
- tests/base.py
- tests/test_zuora_interrupted_sync.py
- Adds `IncludeOrderLineItems` and `IncludeSubscriptions` to the list of unsupported fields for the stream `BillingRun`
- Updates tests to skip empty streams
-
-
https://internal.qlik.dev/general/ways-of-working/code-reviews/#guidelines-for-ai-generated-code
> TDL-27477: Update Unsupported Fields
